alter table "public"."users" drop constraint "users_website_url_key";

drop index if exists "public"."users_website_url_key";


  create table "public"."projects" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "website_url" text not null,
    "created_at" timestamp with time zone default now(),
    "api_key" uuid not null default gen_random_uuid()
      );


alter table "public"."projects" enable row level security;


  create table "public"."users_projects" (
    "user_id" integer not null,
    "project_id" integer not null
      );


alter table "public"."users_projects" enable row level security;

alter table "public"."events" drop column "user_id";

alter table "public"."events" add column "project_id" integer;

alter table "public"."uptime_log" add column "project_id" integer not null;

alter table "public"."users" drop column "website_url";

alter table "public"."users" add column "alert_id" uuid not null default gen_random_uuid();

alter table "public"."users" add column "auth_id" uuid not null;

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX users_projects_pkey ON public.users_projects USING btree (user_id, project_id);

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."users_projects" add constraint "users_projects_pkey" PRIMARY KEY using index "users_projects_pkey";

alter table "public"."events" add constraint "events_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_project_id_fkey";

alter table "public"."uptime_log" add constraint "uptime_log_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."uptime_log" validate constraint "uptime_log_project_id_fkey";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users_projects" add constraint "users_projects_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_projects" validate constraint "users_projects_project_id_fkey";

alter table "public"."users_projects" add constraint "users_projects_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_projects" validate constraint "users_projects_user_id_fkey";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."users_projects" to "anon";

grant insert on table "public"."users_projects" to "anon";

grant references on table "public"."users_projects" to "anon";

grant select on table "public"."users_projects" to "anon";

grant trigger on table "public"."users_projects" to "anon";

grant truncate on table "public"."users_projects" to "anon";

grant update on table "public"."users_projects" to "anon";

grant delete on table "public"."users_projects" to "authenticated";

grant insert on table "public"."users_projects" to "authenticated";

grant references on table "public"."users_projects" to "authenticated";

grant select on table "public"."users_projects" to "authenticated";

grant trigger on table "public"."users_projects" to "authenticated";

grant truncate on table "public"."users_projects" to "authenticated";

grant update on table "public"."users_projects" to "authenticated";

grant delete on table "public"."users_projects" to "service_role";

grant insert on table "public"."users_projects" to "service_role";

grant references on table "public"."users_projects" to "service_role";

grant select on table "public"."users_projects" to "service_role";

grant trigger on table "public"."users_projects" to "service_role";

grant truncate on table "public"."users_projects" to "service_role";

grant update on table "public"."users_projects" to "service_role";


